# Generated by Django 4.1 on 2022-09-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_rename_show_aotdata_anime_rename_song_aotdata_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aotdata',
            name='opedin',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
