# Generated by Django 4.1 on 2022-09-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_aotdata_opedin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aotdata',
            name='opedin',
        ),
    ]
