# Generated by Django 4.1 on 2022-09-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_remove_aotdata_opedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='aotdata',
            name='opedin',
            field=models.CharField(default='Insert Song', max_length=20),
        ),
    ]
