# Generated by Django 4.1 on 2022-09-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_aotdata_opedin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aotdata',
            old_name='anime',
            new_name='show',
        ),
        migrations.RenameField(
            model_name='aotdata',
            old_name='title',
            new_name='song',
        ),
        migrations.AddField(
            model_name='aotdata',
            name='h480',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aotdata',
            name='h720',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aotdata',
            name='mp3',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='aotdata',
            name='annid',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='aotdata',
            name='opedin',
            field=models.CharField(max_length=25),
        ),
    ]
