# Generated by Django 4.1 on 2022-09-04 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0006_rename_anime_aotdata_show_rename_title_aotdata_song_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySongUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_songs', models.ManyToManyField(blank=True, to='search.aotdata')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
