# Generated by Django 4.1 on 2022-09-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_mysonguser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mysonguser',
            old_name='user',
            new_name='MyUser',
        ),
    ]
