# Generated by Django 4.1 on 2022-09-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_rename_user_mysonguser_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='mysonguser',
            name='my_songs',
        ),
        migrations.AddField(
            model_name='mysonguser',
            name='annid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mysonguser',
            name='artist',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mysonguser',
            name='h480',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mysonguser',
            name='h720',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mysonguser',
            name='mp3',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mysonguser',
            name='opedin',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='mysonguser',
            name='show',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mysonguser',
            name='song',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
