# Generated by Django 4.1 on 2022-09-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_songscore_remove_mysonguser_my_songs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysonguser',
            name='annid',
        ),
        migrations.RemoveField(
            model_name='mysonguser',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='mysonguser',
            name='h480',
        ),
        migrations.RemoveField(
            model_name='mysonguser',
            name='h720',
        ),
        migrations.RemoveField(
            model_name='mysonguser',
            name='mp3',
        ),
        migrations.RemoveField(
            model_name='mysonguser',
            name='opedin',
        ),
        migrations.RemoveField(
            model_name='mysonguser',
            name='show',
        ),
        migrations.RemoveField(
            model_name='mysonguser',
            name='song',
        ),
        migrations.AddField(
            model_name='mysonguser',
            name='my_songs',
            field=models.ManyToManyField(blank=True, to='search.aotdata'),
        ),
    ]
