# Generated by Django 4.1 on 2022-09-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_remove_mysonguser_my_songs_mysonguser_my_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysonguser',
            name='my_songs',
        ),
        migrations.AddField(
            model_name='mysonguser',
            name='my_songs',
            field=models.ManyToManyField(blank=True, to='search.aotdata'),
        ),
    ]
