# Generated by Django 4.1 on 2022-09-06 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_remove_mysonguser_my_songs_mysonguser_my_songs'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.aotdata')),
            ],
        ),
        migrations.RemoveField(
            model_name='mysonguser',
            name='my_songs',
        ),
        migrations.AddField(
            model_name='mysonguser',
            name='my_songs',
            field=models.ManyToManyField(through='search.UserList', to='search.aotdata'),
        ),
        
        migrations.AddField(
            model_name='userlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.mysonguser'),
        ),
        migrations.AlterUniqueTogether(
            name='userlist',
            unique_together={('user', 'song')},
        ),
    ]
