# Generated by Django 4.1 on 2022-09-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_rename_song_userlist_mysong_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlist',
            old_name='MySong',
            new_name='ProfileSong',
        ),
        migrations.RenameField(
            model_name='userlist',
            old_name='MySongUser',
            new_name='ProfileUser',
        ),
        migrations.AlterUniqueTogether(
            name='userlist',
            unique_together={('ProfileUser', 'ProfileSong')},
        ),
    ]
