# Generated by Django 4.1 on 2022-09-12 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_rename_mysong_userlist_profilesong_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='songscore',
            name='PossibleScore',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
