# Generated by Django 4.1 on 2022-09-12 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0016_songscore_possiblescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='ProfileScore',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.songscore'),
        ),
    ]
