# Generated by Django 4.1 on 2022-09-12 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0018_alter_userlist_profilescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='ProfileScore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.songscore'),
        ),
    ]
