# Generated by Django 4.1 on 2022-09-12 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0019_alter_userlist_profilescore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='ProfileScore',
        ),
        migrations.DeleteModel(
            name='SongScore',
        ),
    ]
