# Generated by Django 4.1 on 2022-09-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0024_profil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
