# Generated by Django 4.1 on 2022-09-19 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0026_userlist_profilefav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='ProfileFav',
        ),
    ]
